### ISSUE TITLE
Several questions about the implementation and paper

### ISSUE THREAD

**Issue by MasterIzumi** [decisionforce/mmTransformer#13]
Thanks for your great work and the inference code! Here are several questions about this work and it will be very helpful if you give me some hints.

- In the paper, you mentioned that "parallel trajectory proposals can integrate the information from the encoder independently, allowing each single proposal to carry disentangled modality information" (page 3). How to understand the term "disentangled"? Is this means that proposals will focus on different modality automatically? I try to visualize the distribution of endpoints generated by different proposals just like that in Fig. 5, and the result is shown below. The problems are:
    1) The endpoint distribution is not spatially disentangled which is different from Fig. 5. Here, endpoints from different proposals are heavily overlapped. Can I assert the proposed RTS makes the prediction spatially disentangled? So how to understand "each single proposal to carry disentangled modality information"?
    2) It seems that only a few proposals are used in most cases -- {0,1,2,3} are used while {4,5} are always low-confident. Is this unbalanced phenomenon also caused by the vanilla training strategy?

Filter the points with confidences lower than the uniform probability (1/K):
![endpt_f](https://user-images.githubusercontent.com/10687116/146019764-189947b6-ee18-47ce-89c1-56c7c0ff07d2.png)
Without filtering:
![endpt_wof](https://user-images.githubusercontent.com/10687116/146020514-6eaee983-a946-433f-8066-8bcd65a5b867.png)

- In the paper, you mentioned that "we only utilize the decoder of social constructor to update the proposals for target vehicles, instead of all vehicles, in pursuit of higher efficiency" (page 4). However, it seems that the decoder of the social layer (`social_dec`) is not used in the released code, and `social_mem` is simply unsqueezed and concatenated with `social_out`. Is this change intentional? If so, why?

- It seems that the ablative results of the order of transformers are missing. Tab. 2 shows the effectiveness of each module but does not contain how the order of the modules influences prediction results.

Thanks. Always happy to hear from you!

**Comment by Mrmoore98** [comment]
Sorry for the late reply and Thanks for your attention of our work!! I'm really flattered by your carefully review.

Since we don't check the GitHub issues daily. If you have any problem about paper instead of code issue. Then contact us via the email we provided in Readme would be a better choice!

I think your problems are mainly about the model with 36 proposals and RTS, which we haven't released yet.

For problem i. the 'spatially disentangled' is in the context of model training. We distribute the proposals of the model to learn different subset of the original dataset. These ground-truth trajectories are spatially disentangled between the difference sets. We force the model to learn difference region proposal. In the inference stage we have found that the model trained by RTS is position sensitive as we illustrated In the Figure 5. And then we gave the statement you quoted.

For problem ii. Since we haven't deployed the RTS in this model version, so your observation is a natural result.

For problem iii. This is my mistake. I showcase an experimental version of six head proposals mmTrans. This model is rather small compare to the 36 proposals version, and this is an attempt that I try to simplify the structure of the mmTransformer. I will provide the original version of this in the future. This mistake may causes the difference between the performance we released and the results we claimed in paper. I have found that there are still a large room for the social modeling of mmTransformer. The original version of the social encoder and decoder are designed based on the module consistency.

For problem iv. Yes you are right, we haven’t delve into these problem. Since I don’t think there will be huge performance variations if the order are changed.

**Comment by MasterIzumi** [comment]
@Mrmoore98 Thanks for your quick and detailed reply! I think the idea of trajectory proposals in this work is pretty interesting and inspiring.

For problem iv, I think the order (motion -> map -> social) is reasonable in my view. I'm just wondering whether I miss the ablative result since you mentioned "the order of the other transformers has been verified empirically by experimental results shown in Table 2" in the paper. Anyway, I think the experimental result is rich enough for me.

Thanks again for your informative response!

**Comment by Mrmoore98** [comment]
Yes we have some attempts at the very early version of the mmTransformer. The current order is the best at that time. Since you have no more questions, I will close this issue.
