### ISSUE TITLE
What is the detail procedure of manual partition?

### ISSUE THREAD

**Issue by YouSonicAI** [decisionforce/mmTransformer#14]
I have seen the Kmeans procedure described in part D of Appendix, but I cannot find the manual method.
I wonder how to partition in manual method

**Comment by DinghaoXi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我已经收到邮件，会尽快给您回复。by小溪

**Comment by Mrmoore98** [comment]
The results of manual method is similar with the figure below，but I don't recommend using the manual methods, since it needs more efforts than applying the K-means partition and achieves similar results with  K-means partition .
![image](https://user-images.githubusercontent.com/23526256/155162708-e01d4571-cb79-4063-aa71-af75e9661ddc.png)

**Comment by YouSonicAI** [comment]
Got it. Thank you~

**Comment by YouSonicAI** [comment]
> The results of manual method is similar with the figure below，but I don't recommend using the manual methods, since it needs more efforts than applying the K-means partition and achieves similar results with K-means partition . ![image](https://user-images.githubusercontent.com/23526256/155162708-e01d4571-cb79-4063-aa71-af75e9661ddc.png)

Another Question, in part D of Appendix, what is exactly normalization described in line 435 of your paper. Because I cannot figure out what is exactly the 435 line in the paper, so I have to ask you.
