### ISSUE TITLE
Some questions about the paper

### ISSUE THREAD

**Issue by MohammadHossein-Bahari** [decisionforce/mmTransformer#4]
Hello,

Congrats on the nice work!
 It is not clear to me what happens to other agents. It seems that you treat all agents similarly with the same network. 
(a) What happens in motion extractor? Do you feed all histories and then update proposals for all vehicles? 
(b) Is the scene normalized for each agent or you keep it normalized for the target agent?

**Comment by Mrmoore98** [comment]
Sorry for the late reply.

> Hello,
> 
> Congrats on the nice work!
> It is not clear to me what happens to other agents. It seems that you treat all agents similarly with the same network.

Yes, we process all the agents' history trajectories and trajectory proposals in a same way before the social constructor.


> (a) What happens in motion extractor? Do you feed all histories and then update proposals for all vehicles?

Motion extractor is a transformer unit. the implementation of transformer you can refer to this [website](http://nlp.seas.harvard.edu/2018/04/03/attention.html)

Transformer encoder in motion extractor encode each history trajectory into a seqence of features, where the input is a sequence of history trajectory (batchsize, n_agents, history_trajectory_length(20), xy(2)) and the output is a sequence of history features (batchsize, n_agents, history_trajectory_length(20), d_model(128)). 

Trajectory proposals aggerate these hisrtory features by key-query attention in the transformer decoder of motion extractor. Since we treat all agents equally in the motion extrator, trajectory proposals from agent A can only see the agent A's histroy features.

The input of transformer decoder are trajectory proposals (batchsize, n_agents, n_trajectory_proposal(36), d_model(128)) and history features (batchsize, n_agents, history_trajectory_length(20), d_model(128)), and the outputs are trajectory proposals (batchsize, n_agents,  n_trajectory_proposal(36), d_model(128)).

Yes, we update proposals for all vehicles.

> (b) Is the scene normalized for each agent or you keep it normalized for the target agent?

We normalize the position of all the agents' histroy tajectories and scene based on target agent position and angle state at the observation point. 

However, in our recent experiments we found that if you first normalize nearby agent by itself and encode them by motion extractor and then add the relative information between the nearby agent and target agent after the motion extractor to trajectory proposals. The the predictions performance of nearby agents may improve.

**Comment by L4zyy** [comment]
Hi, in the last paragraph you said

> The the predictions performance of nearby agents may improve.

I wonder if the performance of the target agent also improves under this setting or just the performance of nearby agents?

**Comment by jzhang538** [comment]
> Hi, in the last paragraph you said
> 
> > The the predictions performance of nearby agents may improve.
> 
> I wonder if the performance of the target agent also improves under this setting or just the performance of nearby agents?

**Comment by jzhang538** [comment]
> Hi, in the last paragraph you said
> 
> > The the predictions performance of nearby agents may improve.
> 
> I wonder if the performance of the target agent also improves under this setting or just the performance of nearby agents?

Hi,

**Comment by jzhang538** [comment]
> Hi, in the last paragraph you said
> 
> > The the predictions performance of nearby agents may improve.
> 
> I wonder if the performance of the target agent also improves under this setting or just the performance of nearby agents?

Here we simply mean the prediction performance of nearby agents themselves.

**Comment by L4zyy** [comment]
> Here we simply mean the prediction performance of nearby agents themselves.

Got it. Thanks for the quick reply ^ ^
